# Site settings
title: Roberto Reale
subtitle:
email: roberto@reale.me
pec: reale.roberto@pec.it
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/website-beta" # the subpath of your site, e.g. /blog
url: "https://reale.me" # the base hostname & protocol for your site
author: Roberto Reale
street_address:
city: Rome
state:
zip_code:
country: Italy
phone:

# Social settings
social:
  500px_url:
  facebook: rober.reale
  github: reale
  gitlab:
  instagram: robertoreale.ig
  linkedin: robertoreale
  pinterest:
  slack:
  twitter: roberto_reale
  google_scholar: 3oTyeNsAAAAJ
  medium: reale
  youtube: UCptr2ANwqoW_B4MBRocBsbw

# Build settings
markdown: kramdown
