# Site settings
title: Roberto Reale
subtitle:
title_image: /assets/images/cover.jpg
email: roberto@reale.me
pec: reale.roberto@pec.it
description: "Roberto Reale's website"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://reale.me" # the base hostname & protocol for your site
author: Roberto Reale
street_address:
city: Rome
state:
zip_code:
country: Italy
phone:
timezone: Etc/UTC

# Social settings
social:
  500px_url:
  facebook: rober.reale
  github: reale
  gitlab:
  instagram: robertoreale.ig
  linkedin: robertoreale
  pinterest:
  slack:
  twitter: Reale_EU
  #google_scholar: 3oTyeNsAAAAJ
  medium: reale
  youtube: UCptr2ANwqoW_B4MBRocBsbw

# Facebook settings
fb:
  app_id: 1180025952207409
  locale: en_US
  pixel_id: 809031996113072

# Google Analytics
ga_measurement_id: G-L7KNWCTXLY

# Flattr ID
flattr_id: 6200gj

# Disqus shortname
disqus: reale

# Iubenda
iubenda:
  en: 20569279
  fr: 18356222
  it: 59057786

# Build settings
markdown: kramdown

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
