# Site settings
title: Roberto Reale
subtitle:
email: roberto@reale.me
pec: reale.roberto@pec.it
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/website-beta" # the subpath of your site, e.g. /blog
url: "https://reale.me" # the base hostname & protocol for your site
author: Roberto Reale
street_address:
city: Rome
state:
zip_code:
country: Italy
phone:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/rober.reale
github_url: https://github.com/reale
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/robertoreale/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/roberto_reale

# Build settings
markdown: kramdown
