# CircleCI configuration file
#
#
#
version: 2.1

orbs:
  # Install puppeteer and headless chrome in order to run pa11y-ci
  # https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-circleci
  puppeteer: threetreeslight/puppeteer@0.1.2

commands:
  restore_gem_cache:
    description: Restore ruby dependencies cache
    steps:
      - restore_cache:
          keys:
          - v1-gem-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-gem

  install_bundler:
    description: Ensure bundler is installed
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")

  install_dependencies:
    description: Install ruby dependencies with bundler
    steps:
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle

  save_gem_cache:
    description: Save ruby dependencies cache
    steps:
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-gem-{{ checksum "Gemfile.lock" }}

  install_pa11y:
    description: Install Pa11y
    steps:
      - run:
          name: Install Pa11y
          command: sudo npm install -g pa11y-ci --unsafe-perm=true --allow-root

jobs:
  build_and_test:
    docker:
      - image: circleci/ruby:2.5.3-node
    environment:
      - JEKYLL_ENV: production
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - checkout
      - restore_gem_cache
      - install_bundler
      - install_dependencies
      - save_gem_cache
      - install_pa11y
      # build
      - run:
          name: Run build task
          command: bundle exec jekyll build
      # test
      - run:
          name: Run test task
          command: bundle exec htmlproofer ./_site  --check-html --allow-hash-href --empty-alt-ignore --only-4xx --assume-extension --log-level :debug --check-favicon --http-status-ignore 400,403,429
#      - run:
#          name: Run Pa11y task
#          command: pa11y-ci $(find ./_site -name '*.html')
      - persist_to_workspace:
          root: .
          paths:
            - _site
            - .circleci

  deploy_gh_pages:
    docker:
      - image: circleci/ruby:2.5.3-node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4a:80:48:12:8a:b6:9b:c4:54:6b:57:05:c7:44:fd:20"
      - checkout:
          path: /tmp/gh-pages
      - attach_workspace:
          at: .
      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "info@eutopian.eu"
            git config --global user.name "Eutopian CI"
            
            cd /tmp/gh-pages
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .

            cp -a ~/project/_site/. .
            echo "eutopian.eu" > CNAME
            # copy .circleci as well so that the branch filter is honored
            mkdir -p .circleci && cp -a ~/project/.circleci/. .circleci/.

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2

  build:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: gh-pages

      - deploy_gh_pages:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
